spring.application.name=TicketMediator

server.servlet.context-path=/TicketingMediator

server.port=8181

api.base.url=http://localhost:8080/

api.tourists.endpoint.courses=/TicketingApp/course-api/getAllCourses

api.tourists.endpoint.packages=/TicketingApp/api/getPackages
logging.level.org.springframework.web=DEBUG
